---
deployment:
  tasks:
    - export PUBLICPATH=/home/wargadjaja/public_html/store_app
    - export DEPLOYPATH=/home/wargadjaja/projects/karuizawa-lts/karuizawa-phase1.1
    - export COMPOSER_PATH=/usr/local/bin/composer
    - export PHP_PATH=/usr/local/bin/ea-php83
    - /bin/cp -R * $DEPLOYPATH
    - $PHP_PATH $COMPOSER_PATH update --working-dir=$DEPLOYPATH --no-dev
    - /bin/cp -rf public/vendor/* $DEPLOYPATH/public/vendor
    - /bin/cp -rf public/vendor/* $PUBLICPATH/vendor
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -rf $DEPLOYPATH/.cpanel.yml
    - /bin/rm -rf $DEPLOYPATH/.gitignore
    - /bin/cd $DEPLOYPATH
    - $PHP_PATH artisan migrate --force
    - $PHP_PATH artisan storage:link
    - $PHP_PATH artisan config:cache
    - $PHP_PATH artisan route:cache
    - $PHP_PATH artisan view:cache
    - $PHP_PATH -v
